 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
  name: netingress
  labels:
    net: Q-net
 spec:
  ingressClassName: nginx
  rules:
  # q-net- host: www.qnet.com
  http:
    paths:
    - backend:
        service:
          name: nginx-qnet-svc
          port:
            number: 80
        path: /
        pathType: Prefix
        # qc-net
    - host: www.cqnet.com
      http:
        paths:
          - backend:
            service:
              name: nginx-qcnet-svc
              port:
                number: 80
            path: /
            pathType: Prefix