 apiVersion: v1
 kind: PersistentVolume
 metadata:
  name: mysql-a
 labels:
  pv: mysql
  net: Q-net
 spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
  path: /var/lib/mysql-data-1/--
  apiVersion: v1
  kind: PersistentVolume
  metadata:
  name: mysql-b
  labels:
  pv: mysql
  net: Q-net
  spec:
    storageClassName: manual
    capacity:
    storage: 10Gi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
    path: /var/lib/mysql-data-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
name: mysql-c
labels:
  pv: mysql
  net: Q-net
spec:
  storageClassName: manual
  capacity:
  storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
  path: /var/lib/mysql-data-3/